added chances to tasks and removed code to struct testing

diff --git a/install_sublimemerge_dev b/install_sublimemerge_dev
--- a/install_sublimemerge_dev
+++ b/install_sublimemerge_dev
@@ -3,66 +3,115 @@
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
 #
+
+# SUDO_USER only exists during execution of sudo
+# REF: https://stackoverflow.com/questions/7358611/get-users-home-directory-when-they-run-a-script-as-root
+# Global:
+THISSCRIPTNAME=`basename "$0"`
+
+execute_as_sudo(){
+  if [ -z $SUDO_USER ] ; then
+    if [[ -z "$THISSCRIPTNAME" ]] ; then
+    {
+        echo "error You need to add THISSCRIPTNAME vairable like this:" 
+        echo "     THISSCRIPTNAME=\`basename \"\$0\"\`"
+    }
+    else 
+    {
+        if [ -e "./$THISSCRIPTNAME" ] ; then
+        {       
+          sudo "./$THISSCRIPTNAME"
+        }
+        elif ( command -v type "$THISSCRIPTNAME" >/dev/null 2>&1 );  then
+        {
+          echo "sudo sudo sudo "
+          sudo "$THISSCRIPTNAME"
+        }
+        else
+        {
+          echo -e "\033[05;7m*** Failed to find script to recall it as sudo ...\033[0m"
+          exit 1
+        }
+        fi
+    }
+    fi
+    wait
+    exit 0
+  fi
+  # REF: http://superuser.com/questions/93385/run-part-of-a-bash-script-as-a-different-user
+  # REF: http://superuser.com/questions/195781/sudo-is-there-a-command-to-check-if-i-have-sudo-and-or-how-much-time-is-left
+  local CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
+  if [ ${CAN_I_RUN_SUDO} -gt 0 ]; then
+    echo -e "\033[01;7m*** Installing as sudo...\033[0m"
+  else
+    echo "Needs to run as sudo ... ${0}"
+  fi
+}
+execute_as_sudo
+
+USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
+
 load_struct_testing_wget(){
-    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
+    local provider="$USER_HOME/_/clis/execute_command_intuivo_cli/struct_testing"
     [   -e "${provider}"  ] && source "${provider}"
     [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
     ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
 } # end load_struct_testing_wget
 load_struct_testing_wget
+passed Caller user identified:$USER_HOME
 
-get_lastest_sublime_version() {
+
+_version() {
    # 0. Determine where is the latest vesion published
    #    + expected to respond: https://www.sublimemerge.com/
    # 1. Go to page and see current version
    # 2. Extract current version number
    # 3.
-
-
-    # normal local _sublime_string=$(curl -L https://www.sublimemerge.com/  2>/dev/null | sed -n "/<div\ class=\"current_version\">/,/<\/div>/p" | head -1)   # suppress only wget download messages, but keep wget output for variable
+  local PLATFORM="${1}"
+  local PATTERN="${2}"
+   # normal local CODEFILE=$(curl -L https://www.sublimemerge.com/  2>/dev/null | sed -n "/<div\ class=\"current_version\">/,/<\/div>/p" | head -1)   # suppress only wget download messages, but keep wget output for variable
    #    + expected string:     <div class="current_version">Sublime Merge <i>(Build 1119)</i></div>
-    local _sublime_string=$(curl -L https://www.sublimemerge.com/dev  2>/dev/null | sed -n "/<p\ class=\"latest\">/,/<\/div>/p" | head -1)   # suppress only wget download messages, but keep wget output for variable
+    local CODEFILE=$(curl -L https://www.sublimemerge.com/dev  2>/dev/null)
+    local VERSION=$(echo "$CODEFILE" | sed -n "/<p\ class=\"latest\">/,/<\/div>/p" | head -1)   # suppress only wget download messages, but keep wget output for variable
    #    + expected string:      <p class="latest"><i>Version:</i> Build 1118</p>
-    local _sublime_build_line=$(echo "${_sublime_string}" | grep 'Build ....')
+    local _sublime_build_line=$(echo "${VERSION}" | grep 'Build ....')
+    
     if [ -z "${_sublime_build_line}" ] ; then
     {
         echo "error when doing check of line string from website. Got nothing"
-        echo "    _sublime_string: <${_sublime_string}>"
+        echo "    VERSION: <${VERSION}>"
         echo "                      0123456789 123456789 123456789 123456789 123456789 123456789 1234567889 123456789 123456789 123456789 123456789 "
         echo "                                1         2         3         4         5         6          7         8         9        10        11"
         echo "_sublime_build_line: <${_sublime_build_line}>"
         failed "Error"
         exit 69;
     }
-    else
-    {
-        local SUBLIMEDEVLASTESTBUILD=$(echo "${_sublime_build_line}" | cut -c42-45)
-        wait
-        [[ -z "${SUBLIMEDEVLASTESTBUILD}" ]] && failed "Sublime Version not found!"
-        echo "${SUBLIMEDEVLASTESTBUILD}"
-    }
     fi
+    local SUBLIMEDEVLASTESTBUILD=$(echo "${_sublime_build_line}" | cut -c42-45)
+    wait
+    [[ -z "${SUBLIMEDEVLASTESTBUILD}" ]] && failed "Sublime Merge Version not found!"
+    # THOUGHT local TARGETURL=$(echo $CODEFILE | sed s/\</\\n\</g | grep "x86_64.rpm" | sed s/\"/\\n/g | head -2 | tail -1 | sed s@\/@\\n@g | tail -1)
+    # echo SUBLIMEDEVLASTESTBUILD:"${SUBLIMEDEVLASTESTBUILD}"
+    # echo PATTERN:"${PATTERN}" 
+    # echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" 
+    local CODENAME=$(echo "$CODEFILE" | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | head -2 | tail -1 | sed s@\/@\\n@g | tail -1)
+    wait
+    # echo CODENAME:"${CODENAME}" 
+    [[ -z "${CODENAME}" ]] && failed "Sublime Merge Download Url not found!"
+    echo "${CODENAME}" 
+    # exit 1
+    
 }
-download_sublime(){
-  # + expected download url  https://download.sublimetext.com/sublime-merge_build-1119_amd64.deb
-  if ( command -v type wget >/dev/null 2>&1; ) ; then
-   wget --quiet --no-check-certificate "https://download.sublimetext.com/${1}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
+# https://download.sublimetext.com/${1}
 
-  elif ( command -v type curl >/dev/null 2>&1; ); then
-    curl -O "https://download.sublimetext.com/${1}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
-
-  else
-    failed "I cannot find wget or curl to download! https://download.sublimetext.com/${1}"
-  fi
-}
-install_darwin_lastest_sublime_64() {
+_darwin__64() {
     # expected string: https://download.sublimetext.com/sublime_merge_build_1119_mac.zip
-    local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
-    local SUBLIMENAME="sublime_merge_build_{SUBLIMEDEVLASTESTBUILD}_mac.zip"
+    local CODENAME=$(_version "mac" "mac.zip")
+    local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
     local SUBLIMENAME_4_HDUTIL="sublime_merge_build_{SUBLIMEDEVLASTESTBUILD}_mac.dmg"
     wait
     cd ~/Downloads/
-    [ ! -e "${SUBLIMENAME_4_HDUTIL}" ] || download_sublime "${SUBLIMENAME}"
+    [ ! -e "${SUBLIMENAME_4_HDUTIL}" ] || _download "${SUBLIMENAME}"
     unzip "${SUBLIMENAME}"
     echo "${pwd}"
     echo "${SUBLIMENAME_4_HDUTIL}"
@@ -74,47 +123,107 @@ install_darwin_lastest_sublime_64() {
     wait
     sudo hdiutil detach /Volumes/Sublime\ Merge
     wait
-} # end install_darwin_lastest_sublime_64
+} # end _darwin__64
 
-install_linux_lastest_sublime_64() {
-    echo "checking version"
-    local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
-    echo " version ${SUBLIMEDEVLASTESTBUILD}"
-    local SUBLIMENAME="sublime-merge_build-${SUBLIMEDEVLASTESTBUILD}_amd64.deb"
-    echo " looking for file ${SUBLIMENAME} online"
-    wait
-    echo "changing to Downloads folder  ~/Downloads/"
-    cd ~/Downloads/
-    echo "downloading ${SUBLIMENAME}"
-    download_sublime "${SUBLIMENAME}"
+_ubuntu__64() {
+   local CODENAME=$(_version "linux" "amd64.deb")
+   local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
+   file_exists_with_spaces $USER_HOME/Downloads
+   cd $USER_HOME/Downloads
+   _download "${TARGET_URL}"
+   file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
     wait
     echo "installing "
     sudo dpkg -i ${SUBLIMENAME}
     wait
-} # end install_linux_lastest_sublime_64
+} # end _ubuntu__64
 
-install_linux_lastest_sublime_32() {
-    echo "checking version"
-    local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
-    echo " version ${SUBLIMEDEVLASTESTBUILD}"
-    local SUBLIMENAME="sublime-merge_build-${SUBLIMEDEVLASTESTBUILD}_i386.deb"
-    echo " looking for file ${SUBLIMENAME} online"
-    wait
-    echo "changing to Downloads folder  ~/Downloads/"
-    cd ~/Downloads/
-    echo "downloading ${SUBLIMENAME}"
-    download_sublime "${SUBLIMENAME}"
-    wait
-    echo "installing "
-    sudo dpkg -i ${SUBLIMENAME}
-    wait
-} # end install_linux_lastest_sublime_32
+_ubuntu__32() {
+   local CODENAME=$(_version "linux" "i386.deb")
+   local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
+   file_exists_with_spaces $USER_HOME/Downloads
+   cd $USER_HOME/Downloads
+   _download "${TARGET_URL}"
+   file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
 
-install_windows_lastest_sublime_64() {
-    # expected url: https://download.sublimetext.com/sublime_merge_build_1119_x64_setup.exe
-    local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
-    wait
-    local SUBLIMENAME="sublime_merge_build_${SUBLIMEDEVLASTESTBUILD}_x64_setup.exe"
+   sudo dpkg -i ${SUBLIMENAME}
+   wait
+} # end _ubuntu__32
+
+
+_fedora__32() {
+  # local CODENAME="sublime-merge_build-${VERSION}.i386.rpm"
+  local CODENAME=$(_version "linux" "i386.rpm")
+  local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
+  file_exists_with_spaces $USER_HOME/Downloads
+  cd $USER_HOME/Downloads
+  _download "${TARGET_URL}"
+  file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
+  ensure rpm or "Canceling Install. Could not find rpm command to execute install"
+  
+  _try "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
+
+  # provide error handling , once learned goes here. LEarn under if, once learned here.
+  # Start loop while ERROR flag in case needs to try again, based on error 
+ 
+  local msg=$(_try "rpm -ivh \"$USER_HOME/Downloads/${CODENAME}\"" )
+  local ret=$?
+  if [ $ret -gt 0 ] ; then 
+  {
+    failed "${ret}:${msg}"
+    # add error handling knowledge while learning.
+  } 
+  else
+  {
+    passed Install with RPM success!
+  }
+  fi
+  ensure bcompare or "Failed to install Beyond Compare"
+  rm -f "$USER_HOME/Downloads/${CODENAME}"
+  file_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
+} # end _fedora__32
+
+
+_fedora__64() {
+  echo "fedora 64"
+  # https://download.sublimetext.com/sublime-merge-1118-1.x86_64.rpm
+  # sublime-merge-1118-1.x86_64.rpm
+  local CODENAME=$(_version "linux" "x86_64.rpm")
+  echo CODENAME: $CODENAME
+  local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
+  echo TARGET_URL: $TARGET_URL
+  file_exists_with_spaces $USER_HOME/Downloads
+  cd $USER_HOME/Downloads
+  _download "${TARGET_URL}"
+  file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
+  ensure rpm or "Canceling Install. Could not find rpm command to execute install"
+  
+  _try "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
+
+  # provide error handling , once learned goes here. LEarn under if, once learned here.
+  # Start loop while ERROR flag in case needs to try again, based on error 
+
+
+  local msg=$(_try "rpm -ivh \"$USER_HOME/Downloads/${CODENAME}\"" )
+  local ret=$?
+  if [ $ret -gt 0 ] ; then 
+  {
+    failed "${ret}:${msg}"
+    # add error handling knowledge while learning.
+  } 
+  else
+  {
+    passed Install with RPM success!
+  }
+  fi
+  ensure bcompare or "Failed to install Beyond Compare"
+  rm -f "$USER_HOME/Downloads/${CODENAME}"
+  file_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
+} # end _fedora__64
+
+_mingw__64() {
+    local CODENAME=$(_version "win" "exe")
+    local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
     wait
     cd $HOMEDIR
     cd Downloads
@@ -123,23 +232,22 @@ install_windows_lastest_sublime_64() {
     wait
 } # end install_windows_lastest_sublime_64
 
-# check operation systems
-if [[ "$(uname)" == "Darwin" ]] ; then
-  # Do something under Mac OS X platform
-    [[ "$(uname -m)" == "x86_64" ]] && install_darwin_lastest_sublime_64 "$@"
-    [[ "$(uname -m)" == "i686"   ]] && install_darwin_lastest_sublime_64 "$@"
-elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
-  # Do something under GNU/Linux platform
-  # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
-    [[ "$(uname -i)" == "x86_64" ]] && install_linux_lastest_sublime_64 "$@"
-    [[ "$(uname -i)" == "i686"   ]] && install_linux_lastest_sublime_32 "$@"
-elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
-  # Do something under Windows NT platform
-    [[ "$(uname -i)" == "x86_64" ]] && install_windows_lastest_sublime_64 "$*"
-    [[ "$(uname -i)" == "i686"   ]] && install_windows_lastest_sublime_64 "$*"
-  install_windows_lastest_sublime_64 "$*"
-  # nothing here
-fi
+_mingw__32() {
+    local CODENAME=$(_version "win" "exe")
+    local TARGET_URL="https://download.sublimetext.com/${CODENAME}"
+    cd $HOMEDIR
+    cd Downloads
+	    curl -O https://download.sublimetext.com/${CODENAME}
+	    ${CODENAME}
+} # end 
 
+
+_main() {
+  determine_os_and_fire_action
+} # end _main
+
+_main
+
+echo ":)"
 
 
