updated all installs a little better, added sub for phpstorm, updarted visual studio code update to download and install in fedora properly

diff --git a/install_phpstorm b/install_phpstorm
--- a/install_phpstorm
+++ b/install_phpstorm
@@ -19,17 +19,17 @@ execute_as_sudo(){
     {
         if [ -e "./$THISSCRIPTNAME" ] ; then
         {
-        sudo "./$THISSCRIPTNAME"
+          sudo "./$THISSCRIPTNAME"
         }
         elif ( command -v type "$THISSCRIPTNAME" >/dev/null 2>&1 );  then
         {
-        echo "sudo sudo sudo "
-        sudo "$THISSCRIPTNAME"
+          echo "sudo sudo sudo "
+          sudo "$THISSCRIPTNAME"
         }
         else
         {
-        echo -e "\033[05;7m*** Failed to find script to recall it as sudo ...\033[0m"
-        exit 1
+          echo -e "\033[05;7m*** Failed to find script to recall it as sudo ...\033[0m"
+          exit 1
         }
         fi
     }
@@ -46,9 +46,33 @@ execute_as_sudo(){
     echo "Needs to run as sudo ... ${0}"
   fi
 }
-execute_as_sudo
 
-USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
+_get_user_home() {
+  # check operation systems
+  if [[ "$(uname)" == "Darwin" ]] ; then
+    # Do something under Mac OS X platform
+    CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
+    if [ ${CAN_I_RUN_SUDO} -gt 0 ]; then
+      echo -e "\033[01;7m*** Installing as sudo...\033[0m"
+    else
+      echo "Needs to run as sudo ... ${0}"
+      exit 1
+    fi
+    USER_HOME=$(echo "/Users/$SUDO_USER")
+  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+    # Do something under GNU/Linux platform
+    execute_as_sudo
+    USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
+  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+    # Do something under Windows NT platform
+    USER_HOME=$(echo "/Users/$SUDO_USER")
+    # nothing here
+  fi
+
+} # end _get_user_home
+_get_user_home
+
+
 
 load_struct_testing_wget(){
     local provider="$USER_HOME/_/clis/execute_command_intuivo_cli/struct_testing"
@@ -57,7 +81,11 @@ load_struct_testing_wget(){
     ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
 } # end load_struct_testing_wget
 load_struct_testing_wget
-passed Caller user identified:$USER_HOME
+
+passed Caller user identified:$SUDO_USER
+passed Home identified:$USER_HOME
+file_exists_with_spaces "$USER_HOME"
+
 
 
 _version() {
@@ -67,9 +95,9 @@ _version() {
   local PATTERN="${2}"
   # THOUGHT: local CODEFILE=$(curl -d "zz=dl4&platform=linux" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://download-cf.jetbrains.com/ruby/download.php  2>&1;) # suppress only wget download messages, but keep wget output for variable
   local CODEFILE=$(curl -d "zz=dl4&platform=${PLATFORM}" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://download-cf.jetbrains.com/ruby/download.php  2>&1;) # suppress only wget download messages, but keep wget output for variable
-  # THOUGHT: local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "RubyMine*.*.*.*.x86_64.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
+  # THOUGHT: local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "PhpStorm*.*.*.*.x86_64.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
   local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cuet "/")
-  # fedora 32 local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "RubyMine*.*.*.*.i386.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
+  # fedora 32 local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "PhpStorm*.*.*.*.i386.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
   wait
   [[ -z "${CODELASTESTBUILD}" ]] && failed "Beyond Compare Version not found! :${CODELASTESTBUILD}:"
 
@@ -86,8 +114,8 @@ _version() {
 } # end _version
 
 _darwin__64() {
-    local CODENAME=$(_version "mac" "RubyMineOSX*.*.*.*.zip")
-    # THOUGHT        local CODENAME="RubyMineOSX-4.3.3.24545.zip"
+    local CODENAME=$(_version "mac" "PhpStormOSX*.*.*.*.zip")
+    # THOUGHT        local CODENAME="PhpStormOSX-4.3.3.24545.zip"
     local URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
     cd $USER_HOME/Downloads/
     _download "${URL}"
@@ -98,8 +126,8 @@ _darwin__64() {
 } # end _darwin__64
 
 _ubuntu__64() {
-    local CODENAME=$(_version "linux" "RubyMine-*.*.*.*amd64.deb")
-    # THOUGHT          local CODENAME="RubyMine-4.3.3.24545_amd64.deb"
+    local CODENAME=$(_version "linux" "PhpStorm-*.*.*.*amd64.deb")
+    # THOUGHT          local CODENAME="PhpStorm-4.3.3.24545_amd64.deb"
     local URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
     cd $USER_HOME/Downloads/
     _download "${URL}"
@@ -107,8 +135,8 @@ _ubuntu__64() {
 } # end _ubuntu__64
 
 _ubuntu__32() {
-    local CODENAME=$(_version "linux" "RubyMine-*.*.*.*i386.deb")
-    # THOUGHT local CODENAME="RubyMine-4.3.3.24545_i386.deb"
+    local CODENAME=$(_version "linux" "PhpStorm-*.*.*.*i386.deb")
+    # THOUGHT local CODENAME="PhpStorm-4.3.3.24545_i386.deb"
     local URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
     cd $USER_HOME/Downloads/
     _download "${URL}"
@@ -116,8 +144,8 @@ _ubuntu__32() {
 } # end _ubuntu__32
 
 _fedora__32() {
-  local CODENAME=$(_version "linux" "RubyMine*.*.*.*.i386.rpm")
-  # THOUGHT                          RubyMine-4.3.3.24545.i386.rpm
+  local CODENAME=$(_version "linux" "PhpStorm*.*.*.*.i386.rpm")
+  # THOUGHT                          PhpStorm-4.3.3.24545.i386.rpm
   local TARGET_URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
   file_exists_with_spaces $USER_HOME/Downloads
   cd $USER_HOME/Downloads
@@ -140,16 +168,16 @@ _fedora__32() {
     passed Install with RPM success!
   }
   fi
-  ensure RubyMine or "Failed to install Beyond Compare"
+  ensure PhpStorm or "Failed to install Beyond Compare"
   rm -f "$USER_HOME/Downloads/${CODENAME}"
   file_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
 } # end _fedora__32
 
 
 _fedora__64() {
-  # THOUGHT  https://download-cf.jetbrains.com/ruby/RubyMine-2019.3.1.tar.gz
-  local CODENAME=$(_version "linux" "RubyMine*.*.*.tar.gz")
-  CODENAME=$(echo "RubyMine-2019.3.2")
+  # THOUGHT  https://download-cf.jetbrains.com/ruby/phpstorm-2019.3.1.tar.gz
+  local CODENAME=$(_version "linux" "phpstorm*.*.*.tar.gz")
+  CODENAME=$(echo "phpstorm-2019.3.2")
   local TARGET_URL="https://download-cf.jetbrains.com/ruby/${CODENAME}.tar.gz"
   if  it_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}.tar.gz" ; then
   {
@@ -214,47 +242,47 @@ _fedora__64() {
   directory_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
 
 
-  if  it_exists_with_spaces "$USER_HOME/_/software/rubymine" ; then
+  if  it_exists_with_spaces "$USER_HOME/_/software/phpstorm" ; then
   {
      folder_date=$(date +"%Y%m%d")
-     if  it_exists_with_spaces "$USER_HOME/_/software/rubymine_${folder_date}" ; then
+     if  it_exists_with_spaces "$USER_HOME/_/software/phpstorm_${folder_date}" ; then
      {
        warning A backup already exists for today "${ret}:${msg} \n ... adding time"
        folder_date=$(date +"%Y%m%d%H%M")
      }
      fi
-     msg=$(mv "$USER_HOME/_/software/rubymine" "$USER_HOME/_/software/rubymine_${folder_date}")
+     msg=$(mv "$USER_HOME/_/software/phpstorm" "$USER_HOME/_/software/phpstorm_${folder_date}")
      ret=$?
      if [ $ret -gt 0 ] ; then
      {
        warning failed to move backup "${ret}:${msg} \n"
      }
      fi
-     directory_exists_with_spaces "$USER_HOME/_/software/rubymine_${folder_date}"
-     file_does_not_exist_with_spaces "$USER_HOME/_/software/rubymine"
+     directory_exists_with_spaces "$USER_HOME/_/software/phpstorm_${folder_date}"
+     file_does_not_exist_with_spaces "$USER_HOME/_/software/phpstorm"
   }
   fi
   mkdir -p "$USER_HOME/_/software"
   directory_exists_with_spaces "$USER_HOME/_/software"
-  mv "$USER_HOME/Downloads/${CODENAME}" "$USER_HOME/_/software/rubymine"
+  mv "$USER_HOME/Downloads/${CODENAME}" "$USER_HOME/_/software/phpstorm"
   directory_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
-  directory_exists_with_spaces "$USER_HOME/_/software/rubymine"
-  directory_exists_with_spaces "$USER_HOME/_/software/rubymine/bin"
+  directory_exists_with_spaces "$USER_HOME/_/software/phpstorm"
+  directory_exists_with_spaces "$USER_HOME/_/software/phpstorm/bin"
   mkdir -p "$USER_HOME/.local/share/applications"
   directory_exists_with_spaces "$USER_HOME/.local/share/applications"
   mkdir -p "$USER_HOME/.local/share/mime/packages"
   directory_exists_with_spaces "$USER_HOME/.local/share/mime/packages"
-  file_exists_with_spaces "$USER_HOME/_/software/rubymine/bin/rubymine.sh"
+  file_exists_with_spaces "$USER_HOME/_/software/phpstorm/bin/phpstorm.sh"
 
   # Now Proceed to register REF:  https://gist.github.com/c80609a/752e566093b1489bd3aef0e56ee0426c
   ensure cat or "Failed to use cat command does not exists"
   ensure xdg-mime or "Failed to install run xdg-mime"
 
-   cat << EOF > $USER_HOME/_/software/rubymine/bin/mine-open.rb
+   cat << EOF > $USER_HOME/_/software/phpstorm/bin/mine-open.rb
 #!/usr/bin/env ruby
 
-# $USER_HOME/_/software/rubymine/bin/mine-open.rb
-# script opens URL in format rubymine://open?file=%{file}:%{line} in RubyMine
+# $USER_HOME/_/software/phpstorm/bin/mine-open.rb
+# script opens URL in format phpstorm://open?file=%{file}:%{line} in phpstorm
 
 require 'uri'
 
@@ -280,27 +308,27 @@ rescue
 end
 puts arg
 EOF
-  file_exists_with_spaces "$USER_HOME/_/software/rubymine/bin/mine-open.rb"
-  chmod +x $USER_HOME/_/software/rubymine/bin/mine-open.rb
+  file_exists_with_spaces "$USER_HOME/_/software/phpstorm/bin/mine-open.rb"
+  chmod +x $USER_HOME/_/software/phpstorm/bin/mine-open.rb
 
 
-    cat << EOF > $USER_HOME/_/software/rubymine/bin/mine-open.sh
+    cat << EOF > $USER_HOME/_/software/phpstorm/bin/mine-open.sh
 #!/usr/bin/env bash
 #encoding: UTF-8
-# $USER_HOME/_/software/rubymine/bin/mine-open.sh
-# script opens URL in format rubymine://open?file=%{file}:%{line} in RubyMine
+# $USER_HOME/_/software/phpstorm/bin/mine-open.sh
+# script opens URL in format phpstorm://open?file=%{file}:%{line} in phpstorm
 
 echo "\${@}"
 echo "\${@}" >>  $USER_HOME/_/work/velophil/projects/velotermin/requested.log
-$USER_HOME/_/software/rubymine/bin/mine-open.rb \${@}
-filetoopen=\$($USER_HOME/_/software/rubymine/bin/mine-open.rb "\${@}")
+$USER_HOME/_/software/phpstorm/bin/mine-open.rb \${@}
+filetoopen=\$($USER_HOME/_/software/phpstorm/bin/mine-open.rb "\${@}")
 echo filetoopen "\${filetoopen}"
 echo "\${filetoopen}" >>  $USER_HOME/_/work/velophil/projects/velotermin/requestedfiletoopen.log
 mine "\${filetoopen}"
 
 EOF
-  file_exists_with_spaces "$USER_HOME/_/software/rubymine/bin/mine-open.sh"
-  chmod +x $USER_HOME/_/software/rubymine/bin/mine-open.sh
+  file_exists_with_spaces "$USER_HOME/_/software/phpstorm/bin/mine-open.sh"
+  chmod +x $USER_HOME/_/software/phpstorm/bin/mine-open.sh
 
  cat << EOF > $USER_HOME/.local/share/mime/packages/application-x-mine.xml
 <?xml version="1.0" encoding="UTF-8"?>
@@ -316,29 +344,29 @@ EOF
 
 
 
-  cat << EOF > $USER_HOME/.local/share/applications/jetbrains-rubymine.desktop
-# $USER_HOME/.local/share/applications/jetbrains-rubymine.desktop
+  cat << EOF > $USER_HOME/.local/share/applications/jetbrains-phpstorm.desktop
+# $USER_HOME/.local/share/applications/jetbrains-phpstorm.desktop
 [Desktop Entry]
 Encoding=UTF-8
 Version=2019.3.2
 Type=Application
-Name=RubyMine
-Icon=$USER_HOME/_/software/rubymine/bin/rubymine.svg
-Exec="$USER_HOME/_/software/rubymine/bin/rubymine.sh" %f
+Name=phpstorm
+Icon=$USER_HOME/_/software/phpstorm/bin/phpstorm.svg
+Exec="$USER_HOME/_/software/phpstorm/bin/phpstorm.sh" %f
 MimeType=application/x-mine;text/x-mine;text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
 Comment=The Most Intelligent Ruby and Rails IDE
 Categories=Development;IDE;
 Terminal=true
-StartupWMClass=jetbrains-rubymine
+StartupWMClass=jetbrains-phpstorm
 EOF
-  file_exists_with_spaces "$USER_HOME/.local/share/applications/jetbrains-rubymine.desktop"
+  file_exists_with_spaces "$USER_HOME/.local/share/applications/jetbrains-phpstorm.desktop"
 
 
   cat << EOF > $USER_HOME/.local/share/applications/mimeinfo.cache
 # $USER_HOME/.local/share/applications/mimeinfo.cache
 
 [MIME Cache]
-x-scheme-handler/rubymine=mine-open.desktop;
+x-scheme-handler/phpstorm=mine-open.desktop;
 EOF
   file_exists_with_spaces "$USER_HOME/.local/share/applications/mimeinfo.cache"
 
@@ -349,40 +377,40 @@ Encoding=UTF-8
 Version=1.0
 Type=Application
 Terminal=true
-Exec="$USER_HOME/_/software/rubymine/bin/mine-open.sh" %f
-MimeType=application/rubymine;x-scheme-handler/rubymine;
+Exec="$USER_HOME/_/software/phpstorm/bin/mine-open.sh" %f
+MimeType=application/phpstorm;x-scheme-handler/phpstorm;
 Name=MineOpen
 Comment=BetterErrors
 EOF
   file_exists_with_spaces "$USER_HOME/.local/share/applications/mine-open.desktop"
 
-  # xdg-mime default jetbrains-rubymine.desktop text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
-  # xdg-mime default mine-open.desktop x-scheme-handler/rubymine
-  # msg=$(_try "xdg-mime default mine-open.desktop x-scheme-handler/rubymine" )
-  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop x-scheme-handler/rubymine"
-  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop text/rubymine"
-  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop application/rubymine"
-  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-rubymine.desktop x-scheme-handler/x-mine"
-  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-rubymine.desktop text/x-mine"
-  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-rubymine.desktop application/x-mine"
+  # xdg-mime default jetbrains-phpstorm.desktop text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
+  # xdg-mime default mine-open.desktop x-scheme-handler/phpstorm
+  # msg=$(_try "xdg-mime default mine-open.desktop x-scheme-handler/phpstorm" )
+  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop x-scheme-handler/phpstorm"
+  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop text/phpstorm"
+  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop application/phpstorm"
+  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-phpstorm.desktop x-scheme-handler/x-mine"
+  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-phpstorm.desktop text/x-mine"
+  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-phpstorm.desktop application/x-mine"
 
 #   cat << EOF > $USER_HOME/.config/mimeapps.list
 #   cat << EOF > $USER_HOME/.local/share/applications/mimeapps.list
 # [Default Applications]
-# x-scheme-handler/rubymine=mine-open.desktop
-# text/rubymine=mine-open.desktop
-# application/rubymine=mine-open.desktop
-# x-scheme-handler/x-mine=jetbrains-rubymine.desktop
-# text/x-mine=jetbrains-rubymine.desktop
-# application/x-mine=jetbrains-rubymine.desktop
+# x-scheme-handler/phpstorm=mine-open.desktop
+# text/phpstorm=mine-open.desktop
+# application/phpstorm=mine-open.desktop
+# x-scheme-handler/x-mine=jetbrains-phpstorm.desktop
+# text/x-mine=jetbrains-phpstorm.desktop
+# application/x-mine=jetbrains-phpstorm.desktop
 
 # [Added Associations]
-# x-scheme-handler/rubymine=mine-open.desktop;
-# text/rubymine=mine-open.desktop;
-# application/rubymine=mine-open.desktop;
-# x-scheme-handler/x-mine=jetbrains-rubymine.desktop;
-# text/x-mine=jetbrains-rubymine.desktop;
-# application/x-mine=jetbrains-rubymine.desktop;
+# x-scheme-handler/phpstorm=mine-open.desktop;
+# text/phpstorm=mine-open.desktop;
+# application/phpstorm=mine-open.desktop;
+# x-scheme-handler/x-mine=jetbrains-phpstorm.desktop;
+# text/x-mine=jetbrains-phpstorm.desktop;
+# application/x-mine=jetbrains-phpstorm.desktop;
 # EOF
 #   file_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list"
 #   file_exists_with_spaces "$USER_HOME/.config/mimeapps.list"
@@ -390,13 +418,13 @@ ln -fs "$USER_HOME/.config/mimeapps.list" "$USER_HOME/.local/share/applications/
 softlink_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list>$USER_HOME/.config/mimeapps.list"
 
 
-  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/rubymine"
+  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/phpstorm"
   su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/x-mine"
   su - "${SUDO_USER}" -c "xdg-mime query default text/x-mine"
   su - "${SUDO_USER}" -c "xdg-mime query default application/x-mine"
-  su - "${SUDO_USER}" -c "xdg-mime query default text/rubymine"
-  su - "${SUDO_USER}" -c "xdg-mime query default application/rubymine"
-  msg=$(_try "su - \"${SUDO_USER}\" -c \"xdg-mime query default x-scheme-handler/rubymine\"")
+  su - "${SUDO_USER}" -c "xdg-mime query default text/phpstorm"
+  su - "${SUDO_USER}" -c "xdg-mime query default application/phpstorm"
+  msg=$(_try "su - \"${SUDO_USER}\" -c \"xdg-mime query default x-scheme-handler/phpstorm\"")
   ret=$?
   if [ $ret -gt 0 ] ; then
   {
@@ -425,12 +453,12 @@ softlink_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list>
   su - "${SUDO_USER}" -c "touch test12345.js.haml "
   su - "${SUDO_USER}" -c "gio info test12345.js.haml  | grep \"standard::content-type\""
 
-  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/rubymine"
+  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/phpstorm"
   su - "${SUDO_USER}" -c "gio mime x-scheme-handler/x-mine"
   su - "${SUDO_USER}" -c "gio mime text/x-mine"
   su - "${SUDO_USER}" -c "gio mime application/x-mine"
-  su - "${SUDO_USER}" -c "gio mime text/rubymine"
-  su - "${SUDO_USER}" -c "gio mime application/rubymine"
+  su - "${SUDO_USER}" -c "gio mime text/phpstorm"
+  su - "${SUDO_USER}" -c "gio mime application/phpstorm"
   su - "${SUDO_USER}" -c "rm test12345.rb"
   su - "${SUDO_USER}" -c "rm test12345.erb"
   su - "${SUDO_USER}" -c "rm test12345.js.erb"
@@ -444,15 +472,15 @@ softlink_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list>
   # ... /path_to_ruby_project/ ... /config/initializers/better_errors.rb
 
   if defined?(BetterErrors)
-    BetterErrors.editor = \"rubymine://open?file=%{file}:%{line}\"
+    BetterErrors.editor = \"phpstorm://open?file=%{file}:%{line}\"
     BetterErrors.editor = \"x-mine://open?file=%{file}:%{line}\"
   end
   "
 } # end _fedora__64
 
 _mingw__64() {
-    local CODENAME=$(_version "win" "RubyMine*.*.*.*.exe")
-    # THOUGHT        local CODENAME="RubyMine-4.3.3.24545.exe"
+    local CODENAME=$(_version "win" "PhpStorm*.*.*.*.exe")
+    # THOUGHT        local CODENAME="PhpStorm-4.3.3.24545.exe"
     local URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
     cd $HOMEDIR
 	  cd Downloads
@@ -461,8 +489,8 @@ _mingw__64() {
 } # end _mingw__64
 
 _mingw__32() {
-    local CODENAME=$(_version "win" "RubyMine*.*.*.*.exe")
-    # THOUGHT        local CODENAME="RubyMine-4.3.3.24545.exe"
+    local CODENAME=$(_version "win" "PhpStorm*.*.*.*.exe")
+    # THOUGHT        local CODENAME="PhpStorm-4.3.3.24545.exe"
     local URL="https://download-cf.jetbrains.com/ruby/${CODENAME}"
     cd $HOMEDIR
     cd Downloads
