added more ubuntu 22 migrations to pyenv rbenv i3w_caffeine

diff --git a/2tasks_templates_sudo/pyenv b/2tasks_templates_sudo/pyenv
--- a/2tasks_templates_sudo/pyenv
+++ b/2tasks_templates_sudo/pyenv
@@ -3,35 +3,35 @@
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
 
-_package_list_installer() {
-  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
-  local package packages="${@}"
-  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer pyenv" && echo -e "${RESET}" && return 0' ERR
-
-  if ! install_requirements "linux" "${packages}" ; then
-  {
-    warning "installing requirements. ${CYAN} attempting to install one by one"
-    while read package; do
-    {
-      [ -z ${package} ] && continue
-      if ! install_requirements "linux" "${package}" ; then
-      {
-      _err=$?
-      if [ ${_err} -gt 0 ] ; then
-      {
-          echo -e "${RED}"
-          echo failed to install requirements "${package}"
-          echo -e "${RESET}"
-        }
-        fi
-      }
-      fi
-    }
-    done <<< "${packages}"
-  }
-  fi
-} # end _package_list_installer
-
+# _package_list_installer() {
+#   # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+#   local package packages="${@}"
+#   trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer pyenv" && echo -e "${RESET}" && return 0' ERR
+#
+#   if ! install_requirements "linux" "${packages}" ; then
+#   {
+#     warning "installing requirements. ${CYAN} attempting to install one by one"
+#     while read package; do
+#     {
+#       [ -z ${package} ] && continue
+#       if ! install_requirements "linux" "${package}" ; then
+#       {
+#       _err=$?
+#       if [ ${_err} -gt 0 ] ; then
+#       {
+#           echo -e "${RED}"
+#           echo failed to install requirements "${package}"
+#           echo -e "${RESET}"
+#         }
+#         fi
+#       }
+#       fi
+#     }
+#     done <<< "${packages}"
+#   }
+#   fi
+# } # end _package_list_installer
+#
 
 _git_clone_pyenv() {
   trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _git_clone_pyenv pyenv" && echo -e "${RESET}" && return 0' ERR
@@ -134,6 +134,8 @@ fi
 _debian_flavor_install() {
  # export USER_HOME="/home/${SUDO_USER}"
   enforce_variable_with_value USER_HOME "${USER_HOME}"
+	apt-get install  libbz2-dev libsqlite3-dev python-tk python3-tk tk-dev -y
+
   local package packages="
     libreadline-dev
     libbz2-dev
@@ -335,6 +337,7 @@ _ubuntu__64() {
   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
   _debian_flavor_install
 } # end _ubuntu__64
+
 _ubuntu__aarch64() {
   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
   _ubuntu_22__aarch64
diff --git a/2tasks_templates_sudo/rbenv b/2tasks_templates_sudo/rbenv
--- a/2tasks_templates_sudo/rbenv
+++ b/2tasks_templates_sudo/rbenv
@@ -2,35 +2,35 @@
 #
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
-_package_list_installer() {
-  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
-  local package packages="${@}"
-  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer rbenv" && echo -e "${RESET}" && return 0' ERR
-
-  if ! install_requirements "linux" "${packages}" ; then
-  {
-    warning "installing requirements. ${CYAN} attempting to install one by one"
-    while read package; do
-    {
-      [ -z ${package} ] && continue
-      if ! install_requirements "linux" "${package}" ; then
-      {
-        _err=$?
-        if [ ${_err} -gt 0 ] ; then
-        {
-          echo -e "${RED}"
-          echo failed to install requirements "${package}"
-          echo -e "${RESET}"
-        }
-        fi
-      }
-      fi
-    }
-    done <<< "${packages}"
-  }
-  fi
-} # end _package_list_installer
-
+# _package_list_installer() {
+#   # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+#   local package packages="${@}"
+#   trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer rbenv" && echo -e "${RESET}" && return 0' ERR
+#
+#   if ! install_requirements "linux" "${packages}" ; then
+#   {
+#     warning "installing requirements. ${CYAN} attempting to install one by one"
+#     while read package; do
+#     {
+#       [ -z ${package} ] && continue
+#       if ! install_requirements "linux" "${package}" ; then
+#       {
+#         _err=$?
+#         if [ ${_err} -gt 0 ] ; then
+#         {
+#           echo -e "${RED}"
+#           echo failed to install requirements "${package}"
+#           echo -e "${RESET}"
+#         }
+#         fi
+#       }
+#       fi
+#     }
+#     done <<< "${packages}"
+#   }
+#   fi
+# } # end _package_list_installer
+#
 _git_clone() {
   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
   trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO  _git_clone RBENV" && echo -e "${RESET}" && return 0' ERR
@@ -367,6 +367,52 @@ _ubuntu__aarch64() {
   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
   _ubuntu_22__aarch64
 } # end _ubuntu__aarch64
+
+_ubuntu_22__64() {
+  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+  apt update -y
+  trap 'echo -e "${RED}" && echo "ERROR err:$_err failed $0:$LINENO _debian_flavor_install rbenv" && echo -e "${RESET}" && return 0' ERR
+  # Batch 1 18.04
+  local package packages="
+    autoconf
+    bison
+    build-essential
+    libssl-dev
+    libyaml-dev
+    libreadline6-dev
+    zlib1g-dev
+    libncurses5-dev
+    libffi-dev
+    libgdbm-dev
+  "
+  _package_list_installer "${packages}"
+  # Batch 2 20.04
+  local package packages="
+    autoconf
+    bison
+    build-essential
+    libssl-dev
+    libyaml-dev
+    libreadline6-dev
+    zlib1g-dev
+    libncurses5-dev
+    libffi-dev
+    libgdbm6
+    libgdbm-dev
+  "
+  _package_list_installer "${packages}"
+  _git_clone "https://github.com/rbenv/rbenv.git" "${USER_HOME}/.rbenv"
+  _git_clone "https://github.com/rbenv/ruby-build.git" "${USER_HOME}/.rbenv/plugins/ruby-build"
+  local MSG=$(_add_variables_to_bashrc_zshrc)
+  echo "${MSG}"
+  ensure rbenv or "Canceling until rbenv did not install"
+  su - "${SUDO_USER}" -c 'rbenv install -l'
+  su - "${SUDO_USER}" -c 'rbenv install 3.4.2'
+  su - "${SUDO_USER}" -c 'rbenv global 3.4.2'
+  su - "${SUDO_USER}" -c 'rbenv rehash'
+  ensure ruby or "Canceling until ruby is not working"
+  su - "${SUDO_USER}" -c 'ruby -v'
+} # end _ubuntu_22__64
 
 _ubuntu_22__aarch64() {
   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
