updated ruby 3.1.4 for homebrew linux

diff --git a/tasks_templates_sudo/agrivero_jetson b/tasks_templates_sudo/agrivero_jetson
--- a/tasks_templates_sudo/agrivero_jetson
+++ b/tasks_templates_sudo/agrivero_jetson
@@ -1,4 +1,7 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
+#
+# @author Zeus Intuivo <zeus@intuivo.com>
+#
 
 
 _execute_project_command() {
@@ -93,6 +96,36 @@ __download_file_check_checksum() {
   }
   fi
 } # end __download_file_check_checksum
+
+_package_list_installer() {
+  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+  local package packages="${@}"
+  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer agri_pd" && echo -e "${RESET}" && return 0' ERR
+
+  if ! install_requirements "linux" "${packages}" ; then
+  {
+    warning "installing requirements. ${CYAN} attempting to install one by one"
+    while read package; do
+    {
+      [ -z ${package} ] && continue
+      if ! install_requirements "linux" "${package}" ; then
+      {
+        _err=$?
+        if [ ${_err} -gt 0 ] ; then
+        {
+          echo -e "${RED}"
+          echo failed to install requirements "${package}"
+          echo -e "${RESET}"
+        }
+        fi
+      }
+      fi
+    }
+    done <<< "${packages}"
+  }
+  fi
+} # end _package_list_installer
+
 
 __passively_try_to_connect_to_wifi_but_continue_if_fails() {
   ensure nmcli or "nmcli is needed to connect ot wifi is not working - Install network-manager"
