improved rbenv and i3 installs

diff --git a/tasks_templates_sudo/i3 b/tasks_templates_sudo/i3
--- a/tasks_templates_sudo/i3
+++ b/tasks_templates_sudo/i3
@@ -38,12 +38,16 @@ _debian_flavor_install() {
 
 } # end _debian_flavor_install
 
-_redhat_flavor_install() {
+_fedora_37__64() {
   enforce_variable_with_value USER_HOME "${USER_HOME}"
   echo "REF: https://fedoraproject.org/wiki/I3_guide#First_Login"
   echo "REF: https://fedoramagazine.org/getting-started-i3-window-manager/"
-  dnf builddep i3 -y --allowerasing
-  dnf builddep kitty -y --allowerasing
+  anounce_command 'dnf group install "KDE (K Desktop Environment)" -y --allowerasing'
+  anounce_command 'dnf group install "i3 desktop" -y --allowerasing'
+  anounce_command dnf builddep i3 -y --allowerasing
+  anounce_command dnf install i3 -y --allowerasing
+  anounce_command dnf builddep kitty -y --allowerasing
+  anounce_command dnf install kitty -y --allowerasing
   if (
   install_requirements "linux" "
     bzip2-devel
@@ -56,11 +60,10 @@ _redhat_flavor_install() {
     rust-bzip2-devel
     bzip2
     yakuake
-    i3 
-    i3status 
-    i3lock 
-    dmenu 
+    i3
+    i3status
     i3lock
+    dmenu
     feh
     conky
     dunst
@@ -76,7 +79,7 @@ _redhat_flavor_install() {
     terminator
     rhythmbox
     totem
-    thunar
+    # thunar
     tmux
     py3status
     # until now no issues with boot or breaking gnome brightness
@@ -84,8 +87,10 @@ _redhat_flavor_install() {
     arandr
     brightnessctl
     htop
+    btop
+    bpytop
     polybar
-    python-mpd2
+    # python-mpd2
   "
   ); then
     {
@@ -96,19 +101,68 @@ _redhat_flavor_install() {
       echo "something failed while installing err:$?"
     }
   fi
-  su - "${SUDO_USER}" -c 'brew install libxscrnsaver libnotify bzip2 freetype2'
 
-  su - $SUDO_USER -c 'brew install the_platinum_searcher'
-  su - $SUDO_USER -c 'pip3 install python-mpd'
-  su - $SUDO_USER -c 'pip install python-mpd'
-  verify_is_installed "
+	anounce brew install libxscrnsaver libnotify bzip2 freetype2
+	if su - "${SUDO_USER}" -c 'brew install libxscrnsaver libnotify bzip2 freetype2' ; then
+    {
+      echo "All installed no error"
+    }
+    else
+    {
+      echo "something failed while installing err:$?"
+    }
+  fi
+  anounce brew install the_platinum_searcher
+  if su - "${SUDO_USER}" -c "brew install the_platinum_searcher" ; then
+    {
+      echo "All installed no error"
+    }
+    else
+    {
+      echo "something failed while installing err:$?"
+    }
+  fi
+  anounce pip3 install python-mpd2
+  if su - "${SUDO_USER}" -c 'pip3 install python-mpd2'; then
+    {
+      echo "All installed no error"
+    }
+    else
+    {
+      echo "something failed while installing err:$?"
+    }
+  fi
+  anounce pip install python-mpd2
+  if su - "${SUDO_USER}" -c 'pip install python-mpd2'; then
+    {
+      echo "All installed no error"
+    }
+    else
+    {
+      echo "something failed while installing err:$?"
+    }
+  fi
+
+  if verify_is_installed "
     unzip
     curl
     wget
     tar
     xset
-  "
+  " ; then
+    {
+      echo "All installed no error"
+    }
+    else
+    {
+      echo "something failed while installing err:$?"
+    }
+  fi
   echo "End of install tasks should be installed. I don't know what to do next... "
+} # _fedora_37__64
+
+_redhat_flavor_install() {
+  _fedora_37__64
 } # end _redhat_flavor_install
 
 _arch_flavor_install() {
@@ -144,26 +198,30 @@ _fedora__32() {
 } # end _fedora__32
 
 _fedora__64() {
-  _redhat_flavor_install
-} # end _fedora__64
-
-_fedora_37_64() {
-  _fedora_40__64 
-  
-} # end _fedora_37__64
-
-_fedora_37__64() {
   trap "echo Error:$?" ERR INT
   local _parameters="${*-}"
   local -i _err=0
-  _fedora_40__64 "${_parameters-}"
+  _fedora_37__64 "${_parameters-}"
   _err=$?
   if [ ${_err} -gt 0 ] ; then
   {
     failed "$0:$LINENO while running callsomething above _err:${_err}"
   }
   fi
-} # end _fedora_37__64
+} # end _fedora__64
+
+_deepin_39__64() {
+  trap "echo Error:$?" ERR INT
+  local _parameters="${*-}"
+  local -i _err=0
+  _fedora_37__64 "${_parameters-}"
+  _err=$?
+  if [ ${_err} -gt 0 ] ; then
+  {
+    failed "$0:$LINENO while running callsomething above _err:${_err}"
+  }
+  fi
+} # end _deepin_39__64
 
 
 _fedora_40__64() {
@@ -184,10 +242,10 @@ _fedora_40__64() {
     rust-bzip2-devel
     bzip2
     yakuake
-    i3 
-    i3status 
-    i3lock 
-    dmenu 
+    i3
+    i3status
+    i3lock
+    dmenu
     i3lock
     feh
     conky
