added added nvm pyenv rbenv whatsapp installers

diff --git a/tasks_templates_sudo/pyenv b/tasks_templates_sudo/pyenv
--- a/tasks_templates_sudo/pyenv
+++ b/tasks_templates_sudo/pyenv
@@ -5,7 +5,7 @@
 
 _debian_flavor_install() {
   sudo_it
-  export USER_HOME="/home/${SUDO_USER}"
+  # export USER_HOME="/home/${SUDO_USER}"
   enforce_variable_with_value USER_HOME "${USER_HOME}"
   install_requirements "linux" "
     libreadline-dev
@@ -16,14 +16,15 @@ _debian_flavor_install() {
     tk-dev
     git
   "
-#  verify_is_installed "
-#    libreadline-dev
-#    libbz2-dev
-#    libsqlite3-dev
-#    git
-# "
- _git_clone_pyenv
- _add_variables_to_bashrc_zshrc
+  #  verify_is_installed "
+  #    libreadline-dev
+  #    libbz2-dev
+  #    libsqlite3-dev
+  #    git
+  # "
+  _git_clone_pyenv
+  local MSG=$(_add_variables_to_bashrc_zshrc)
+  echo "${MSG}"
 
 } # end _debian_flavor_install
 
@@ -72,31 +73,32 @@ _redhat_flavor_install() {
     dnf groupinstall 'Development Tools' -y
   }
   fi
-#  verify_is_installed "
-#    # RedHat Flavor only
-#    readline-devel
-#    bzip2-devel
-#    # sqlite
-#    sqlite-devel
-#    # sqlite-tcl
-#    # sqlite-jdbc
-#    # sqlitebrowser
-#    make
-#    automake
-#    cmake
-#    gcc
-#    libtool-ltdl-devel
-#    git
-#    zlib-devel
-#    bzip2
-#    openssl-devel
-#    xz
-#    xz-devel
-#    libffi-devel
-#    findutils
-# "
- _git_clone_pyenv
- _add_variables_to_bashrc_zshrc
+  #  verify_is_installed "
+  #    # RedHat Flavor only
+  #    readline-devel
+  #    bzip2-devel
+  #    # sqlite
+  #    sqlite-devel
+  #    # sqlite-tcl
+  #    # sqlite-jdbc
+  #    # sqlitebrowser
+  #    make
+  #    automake
+  #    cmake
+  #    gcc
+  #    libtool-ltdl-devel
+  #    git
+  #    zlib-devel
+  #    bzip2
+  #    openssl-devel
+  #    xz
+  #    xz-devel
+  #    libffi-devel
+  #    findutils
+  # "
+  _git_clone_pyenv
+  local MSG=$(_add_variables_to_bashrc_zshrc)
+  echo "${MSG}"
 } # end _redhat_flavor_install
 
 _git_clone_pyenv() {
@@ -119,7 +121,7 @@ _git_clone_pyenv() {
 } # _git_clone_pyenv
 
 _add_variables_to_bashrc_zshrc(){
- local PYENV_SH_CONTENT='
+  local PYENV_SH_CONTENT='
 
 # PYENV
 export PYENV_ROOT="'${USER_HOME}'/.pyenv"
@@ -128,19 +130,32 @@ eval "$(pyenv init -)"
 eval "$(pyenv virtualenv-init -)"
 
 '
- _if_not_contains "${USER_HOME}/.bashrc"  "# PYENV" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.bashrc"
- _if_not_contains "${USER_HOME}/.bashrc"  "PYENV_ROOT" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.bashrc"
- _if_not_contains "${USER_HOME}/.bashrc"  "pyenv init" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.bashrc"
- _if_not_contains "${USER_HOME}/.zshrc"  "# PYENV" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.zshrc"
- _if_not_contains "${USER_HOME}/.zshrc"  "PYENV_ROOT" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.zshrc"
- _if_not_contains "${USER_HOME}/.zshrc"  "pyenv init" &&  echo "${PYENV_SH_CONTENT}" >> "${USER_HOME}/.zshrc"
- "${USER_HOME}/.pyenv/bin/pyenv" doctor
-
+  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc pyenv" && echo -e "${RESET}" && return 0' ERR
+  echo "${PYENV_SH_CONTENT}"
+  local INITFILE INITFILES="
+   .bashrc
+   .zshrc
+   .bash_profile
+   .profile
+   .zshenv
+   .zprofile
+  "
+  while read INITFILE; do
+  {
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "# PYENV" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "PYENV_ROOT" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "pyenv init" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+  }
+  done <<< "${INITFILES}"
+  "${USER_HOME}/.pyenv/bin/pyenv" doctor
 } # _add_variables_to_bashrc_zshrc
 
 _arch_flavor_install() {
-  sudo pacman -S tk
-  echo "Procedure not yet implemented. I don't know what to do."
+  pacman -S tk -y
+  _git_clone_pyenv
+  local MSG=$(_add_variables_to_bashrc_zshrc)
+  echo "${MSG}"
+
 } # end _readhat_flavor_install
 
 _arch__32() {
diff --git a/tasks_templates_sudo/rbenv b/tasks_templates_sudo/rbenv
--- a/tasks_templates_sudo/rbenv
+++ b/tasks_templates_sudo/rbenv
@@ -1,31 +1,110 @@
+#!/usr/bin/env bash
+#
+# @author Zeus Intuivo <zeus@intuivo.com>
+#
+_git_clone() {
+  local _source="${1}"
+  local _target="${2}"
+  if  it_exists_with_spaces "${_target}" ; then
+  {
+    cd "${_target}"
+    git fetch
+    git pull
+  }
+  else
+  {
+   git clone "${_source}" "${_target}"
+  }
+  fi
+} # _git_clone
 
-_debian_flavor_install() {
-  # 18.04
-  sudo apt update -y
-  sudo apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev -y
-  # 20.04
-  sudo apt update -y
-  sudo apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev -y
+_add_variables_to_bashrc_zshrc(){
+  local RBENV_SH_CONTENT='
 
-  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
-  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
-  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
-  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile
-  echo 'eval "$(rbenv init -)"' >> ~/.bashrc
-  echo 'eval "$(rbenv init -)"' >> ~/.zshrc
-  type rbenv
-  export PATH="$HOME/.rbenv/bin:$PATH"
+# RBENV
+export RBENV_ROOT="'${USER_HOME}'/.rbenv"
+export PATH="'${USER_HOME}'/.rbenv/bin:${PATH}"
+eval "$(rbenv init -)"
+eval "$(rbenv virtualenv-init -)"
+
+' 
+  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc rbenv" && echo -e "${RESET}" && return 0' ERR
+  echo "${RBENV_SH_CONTENT}"
+  local INITFILE INITFILES="
+   .bashrc
+   .zshrc
+   .bash_profile
+   .profile
+   .zshenv
+   .zprofile
+  "
+  while read INITFILE; do
+  { 
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "# RBENV" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "RBENV_ROOT" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+    _if_not_contains "${USER_HOME}/${INITFILE}"  "rbenv init" ||  echo "${RBENV_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+  }
+  done <<< "${INITFILES}"
+  # type rbenv
+  export PATH="${USER_HOME}/.rbenv/bin:${PATH}"
+  cd "${USER_HOME}/.rbenv/bin"
   eval "$(rbenv init -)"
-  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
+
+  rbenv doctor
   rbenv install -l
   rbenv install 2.6.5
   rbenv global 2.6.5
   rbenv rehash
   ruby -v
+
+} # _add_variables_to_bashrc_zshrc
+
+_debian_flavor_install() {
+  apt update -y
+  install_requirements "linux" "
+    # Batch 1 18.04
+    autoconf
+    bison
+    build-essential
+    libssl-dev
+    libyaml-dev
+    libreadline6-dev
+    zlib1g-dev
+    libncurses5-dev
+    libffi-dev
+    libgdbm5
+    libgdbm-dev
+  "
+  install_requirements "linux" "
+    # Batch 2 20.04
+    autoconf
+    bison
+    build-essential
+    libssl-dev
+    libyaml-dev
+    libreadline6-dev
+    zlib1g-dev
+    libncurses5-dev
+    libffi-dev
+    libgdbm6
+    libgdbm-dev
+  "
+  _git_clone "https://github.com/rbenv/rbenv.git" "${USER_HOME}/.rbenv"
+  _git_clone "https://github.com/rbenv/ruby-build.git" "${USER_HOME}/.rbenv/plugins/ruby-build"
+  local MSG=$(_add_variables_to_bashrc_zshrc)
+  echo "${MSG}"
 } # end _debian_flavor_install
 
 _redhat_flavor_install() {
-  echo "Procedure not yet implemented. I don't know what to do."
+  dnf build-dep rbenv -vy
+  _git_clone "https://github.com/rbenv/rbenv.git" "${USER_HOME}/.rbenv"
+  _git_clone "https://github.com/rbenv/ruby-build.git" "${USER_HOME}/.rbenv/plugins/ruby-build"
+  _add_variables_to_bashrc_zshrc
+  rbenv install -l
+  rbenv install 2.6.5
+  rbenv global 2.6.5
+  rbenv rehash
+  ruby -v
 } # end _redhat_flavor_install
 
 _arch_flavor_install() {
