added changes to rust and brew

diff --git a/tasks_templates_sudo/rust b/tasks_templates_sudo/rust
--- a/tasks_templates_sudo/rust
+++ b/tasks_templates_sudo/rust
@@ -1,4 +1,75 @@
 #!/usr/bin/bash
+alias egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
+_add_variables_to_bashrc_zshrc(){
+  # trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc cargo" && echo -e "${RESET}" && return 0' ERR
+  local FINDCARGO="/opt/homecargo/bin/cargo"
+  
+  if [[ -e "${USER_HOME}/.cargo/bin/cargo" ]] ; then
+  {
+    FINDCARGO="${USER_HOME}/.cargo"
+  }
+  elif [[ -e "/root/.cargo/bin/cargo" ]] ; then
+  {
+    FINDCARGO="/root/.cargo"
+  }
+  elif [[ -e "/opt/cargo/bin/cargo" ]] ; then
+  {
+    FINDCARGO="/opt/cargo"
+  }
+  fi
+
+  local CARGO_SH_CONTENT='
+
+# CARGO - RUST
+source "'${FINDCARGO}'/env"
+
+'
+  echo "${CARGO_SH_CONTENT}"
+  local INITFILE INITFILES="
+   .bashrc
+   .zshrc
+   .bash_profile
+   .profile
+   .zshenv
+   .zprofile
+  "
+  local changed_files=""
+  while read INITFILE; do
+  {
+    [ -z ${INITFILE} ] && continue
+    [[ ! -e "${USER_HOME}/${INITFILE}" ]] && continue
+    Checking "${USER_HOME}/${INITFILE}"
+    chown "${SUDO_USER}" "${USER_HOME}/${INITFILE}"
+    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) || Configuring "${USER_HOME}/${INITFILE}"
+    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) && Skipping configuration for "${USER_HOME}/${INITFILE}"
+    #                             filename            value          || do this .............
+    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) || echo -e "${CARGO_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
+    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) && changed_files="${changed_files} \"${USER_HOME}/${INITFILE}\" "
+
+    [[ ! -e "${HOME}/${INITFILE}" ]] && continue
+    Checking "${HOME}/${INITFILE}"
+    # chown "${SUDO_USER}" "${HOME}/${INITFILE}"
+    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) || Configuring "${HOME}/${INITFILE}"
+    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) && Skipping configuration for "${HOME}/${INITFILE}"
+    #                             filename            value          || do this .............
+    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) || echo -e "${CARGO_SH_CONTENT}" >> "${HOME}/${INITFILE}"
+    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) && changed_files="${changed_files} \"${HOME}/${INITFILE}\" "
+
+    
+  }
+  done <<< "${INITFILES}"
+  # if it_exists /home/linuxcargo ; then
+  # {
+  #   rm -rf /home/linuxcargo
+  # }
+  # fi
+  file_exists_with_spaces "${FINDCARGO}"
+  source "${FINDCARGO}/env"
+  Checking "all files changed files command for you" :
+  echo "sudo vim ${changed_files}"
+  echo "sudo nano ${changed_files}"
+} # _add_variables_to_bashrc_zshrc
+
 
 _debian_flavor_install() {
   # trap  '_trap_on_exit $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  EXIT
@@ -26,29 +97,37 @@ _debian_flavor_install() {
     wget
     tar
   "
-	export ARCHFLAGS="-arch $(uname -m)"
+  export ARCHFLAGS="-arch $(uname -m)"
   ARCHFLAGS="-arch $(uname -m)" curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
-	su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
+  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo"
+  chmod -R 755 "${USER_HOME}/.cargo"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
+ #  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
+ if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
+          {
+                  echo "oops"
+          }
+  fi
+
+  _add_variables_to_bashrc_zshrc
+  rustup default stable
+  su - "${SUDO_USER}" -c "rustup default stable" 
 } # end _debian_flavor_install
 
 _redhat_flavor_install() {
-  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
   enforce_variable_with_value USER_HOME "${USER_HOME}"
-  if 
-		(
-    install_requirements "linux" "
-      base64
+  if (install_requirements "linux" "
       unzip
       curl
       wget
-      ufw
-      nginx
     "
     ); then
-    {
-      apt install base64 -y
-      apt install unzip -y
-    }
+  {
+      echo "warning: failed to install some deps"
+  }
   fi
   verify_is_installed "
     unzip
@@ -56,9 +135,22 @@ _redhat_flavor_install() {
     wget
     tar
   "
-	export ARCHFLAGS="-arch $(uname -m)" 
-  ARCHFLAGS="-arch $(uname -m)" curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
-	su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
+  export ARCHFLAGS="-arch $(uname -m)" 
+  ARCHFLAGS="-arch $(uname -m)"  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo" 
+  chmod -R 755 "${USER_HOME}/.cargo"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
+  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
+  if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
+	  {
+		  echo "oops"
+	  }
+  fi
+
+  _add_variables_to_bashrc_zshrc
+  rustup default stable
+  su - "${SUDO_USER}" -c "rustup default stable" 
 } # end _redhat_flavor_install
 
 _arch_flavor_install() {
